# Generated by Django 3.2.15 on 2022-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0004_alter_question_optionc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='optionc',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='blog_image/'),
        ),
    ]
